### ISSUE TITLE
purl redirect of omit

### ISSUE THREAD

**Issue by Huang-OMIT** [OmniSearch/omit#1]
The current purl redirect of omit ("http://soc.southalabama.edu/~huang/OMIT/Ontology/OMIT.owl") needs to be changed to: https://raw.githubusercontent.com/OmniSearch/omit/master/src/ontology/omit.owl

**Comment by alanruttenberg** [comment]
I've put in the change.
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/omit.yml
Should be live in a bit.
Alan

**Comment by Huang-OMIT** [comment]
It's working! Thanks Alan!
