### ISSUE TITLE
Some quick fixes in omit.owl

### ISSUE THREAD

**Issue by Huang-OMIT** [OmniSearch/omit#2]
(1) Create a new OMIT class "MeSH_term" to replace the imported term "phenotype"

(2) As far as I can tell, the class "xsd_string" is not used at all. If this is the case, we can completely remove the imports.owl file - all classes in this file are already included in various xxx-imports.owl files from the ncro.owl, EXCEPT FOR "phenotype" and "xsd_string"

(3) Clean up the files at https://github.com/OmniSearch/omit/tree/master/src/ontology, following the ncro style:
  - We only need: omit.owl, omit.obo, ncro.owl, catalog-v001.xml, and (optional) README.md, 
  - Move all other files to "Obsolete"
  - Create a new folder "ontofox-inputs" for future use (eventually we will create ncro-imports.owl to replace ncro.owl, and will need ncro.txt in the "ontofox-inputs" folder)

**Comment by Huang-OMIT** [comment]
This is a test message b/c I didn't receive an email about this issue.

**Comment by Huang-OMIT** [comment]
Alan: How to set up the email notification for issues? Just like in ncro tracker... Thx!

**Comment by Huang-OMIT** [comment]
My setting was indeed "Watching"

**Comment by harrisonstrachan** [comment]
Replaced phenotype class with MeSH_term class.
Removed xsd_string class.
Moved all obsolete files.
Created ontofox-imports directory.

**Comment by Huang-OMIT** [comment]
Both ncro.owl and catalog-v001.xml, especially the former, are needed in src/ontology.

**Comment by Huang-OMIT** [comment]
Thanks Harrison!
