### ISSUE TITLE
Amino Acids, Peptides, and Proteins class is under "quality"

### ISSUE THREAD

**Issue by ddooley** [OmniSearch/omit#9]
Can "Amino Acids, Peptides, and Proteins" http://purl.obolibrary.org/obo/OMIT_0002019 be moved from its current "quality > MeSH Terms > Chemicals and Drug Category" path over to "molecular entity"?  Most of the other "Chemicals and Drug Category" subclasses need to be moved too it seems?!

**Comment by ddooley** [comment]
Any updates on this?
What I've discovered is that most MeSH Terms seem inappropriately placed under quality.  Can the MeSH branch be moved up to Entity level?

**Comment by Huang-OMIT** [comment]
We would like to keep the MeSH terms in their current positions for now. Thanks!
